#development:
#  launch_scheduled_checks:
#    class: LaunchScheduledChecksJob
#    schedule: every second
production:
  monitored_endpoints__perform_scheduled_checks:
    class: MonitoredEndpoint::PerformScheduledChecksJob
    schedule: every minute

